import { Router } from "express";
import { renderAllJobs, renderNewJob, handleNewJob, renderJobDetails, renderUpdateJob, handleUpdateJob, handleDeleteJob, handleCloseJob, handleApplyToJob, downloadResume, renderApplicants, updateApplicationStatus } from "../controllers/job.controller.js";
import { isAuthenticated, requireEmailVerified, requireJobOwner } from "../middleware/auth.js";
import { isRecruiter } from "../middleware/isRecruiter.js";
import { upload } from "../middleware/upload.js";
import { validate } from "../middleware/validate.js";
import { applyLimiter } from "../middleware/rateLimit.js";
import { verifyCsrfToken } from "../middleware/csrf.js";
import { jobValidators, applyValidators, recruiterReviewValidators } from "../validators/index.js";

const router = Router();
router.get("/", renderAllJobs);
router.get("/new", isAuthenticated, isRecruiter, requireEmailVerified, renderNewJob);
router.post("/new", isAuthenticated, isRecruiter, requireEmailVerified, verifyCsrfToken, jobValidators, validate("/jobs/new"), handleNewJob);
router.get("/:id", renderJobDetails);
router.get("/:id/edit", isAuthenticated, isRecruiter, requireEmailVerified, requireJobOwner, renderUpdateJob);
router.post("/:id/edit", isAuthenticated, isRecruiter, requireEmailVerified, requireJobOwner, verifyCsrfToken, jobValidators, validate((req) => `/jobs/${req.params.id}/edit`), handleUpdateJob);
router.post("/:id/delete", isAuthenticated, isRecruiter, requireEmailVerified, requireJobOwner, verifyCsrfToken, handleDeleteJob);
router.post("/:id/close", isAuthenticated, isRecruiter, requireEmailVerified, requireJobOwner, verifyCsrfToken, handleCloseJob);
router.post("/:id/apply", isAuthenticated, requireEmailVerified, applyLimiter, upload.single("resume"), verifyCsrfToken, applyValidators, validate((req) => `/jobs/${req.params.id}`), handleApplyToJob);
router.get("/:id/applicants/:applicationId/resume", isAuthenticated, isRecruiter, requireEmailVerified, requireJobOwner, downloadResume);
router.get("/:id/applicants", isAuthenticated, isRecruiter, requireEmailVerified, requireJobOwner, renderApplicants);
router.post("/:id/applicants/:applicationId", isAuthenticated, isRecruiter, requireEmailVerified, requireJobOwner, verifyCsrfToken, recruiterReviewValidators, validate((req) => `/jobs/${req.params.id}/applicants`), updateApplicationStatus);
export default router;
